# Generated by Django 5.0.14 on 2025-09-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_hours',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
